### PR TITLE
Delete Key as a reverse Backspace

### PR DESCRIPTION
**Pull request by srifqi**
Basically, Delete Key is same as pressing Right Key once and then pressing Backspace Key.
KBD_END_KEY_ID is now 0x10100A (was 0x101010).
Some code style fixes.

### CODE REVIEW

**Comment by amanuel2** [comment]
Ill test if via cloning your branch in some. then merge. Thankss!!! :D

**Comment by amanuel2** [comment]
Very sorry for the lateee response.. been busy with midterms.

**Comment by amanuel2** [comment]
There is a bug to this which basically type "bobby" move your cursor to last "b" and press delete to delete y you get this : 

http://i.imgur.com/nNYMxbR.png . 

also when you press delete it isnt suppose to go forward in the character just stay the same..

**Comment by srifqi** [comment]
First, as for now, <kbd>Delete</kbd> will works this way. Second, I'll try to check that bug.

**Comment by double-fault** [comment]
heh, this is wrong. The <kbd>Delete</kbd> key is **not in all** cases right arrow key and backspace. I'll implement this later. 

I'm going to try this out now.

**Comment by double-fault** [comment]
I'll do the bugfixes if something is wrong, and will Revert this commit if something is _totally_ wrong.

**Comment by double-fault** [comment]
Reverted this. The functionality works, but the printing is wrong.

 For example, if I type `abcd`, and put the cursor on `c`. Now, if I press <kbd>Delete</kbd>, it deletes the character `c` inside like it should, but on the screen it deletes `d`. So on the screen it is `abc` but once I press enter, it shows `abd` which is what should also be printed.

**Comment by double-fault** [comment]
See this, I have implemented it: https://github.com/Bone-Project/BoneOS/issues/191

**Comment by double-fault** [comment]
Also, Delete key is **not** just right key and backspace.

**Pull request merged**
