### PR TITLE
Add nasm and supervisor to setup.sh (macOS)

### PR DESCRIPTION
**Pull request by xrisk**

### CODE REVIEW

**Comment by srifqi** [comment]
The check in TravisCI have failed.

**Comment by xrisk** [comment]
@sriqfi it actually failed from before, see commit history.

**Comment by amanuel2** [comment]
@srifqi Yes thats right , i have pushed failed code so i can have update

**Review by amanuel2 — APPROVED** [review]
Approve nasm and supervisor additions.

**Pull request merged**
