### PR TITLE
RTC and time command

### PR DESCRIPTION
**Pull request by srifqi**
Reworking RTC and also adding ```time``` command.

### CODE REVIEW

**Comment by amanuel2** [comment]
Can  u make  sure your headers are extern?  And can u seperate the rtc to rtc_get_month etc etc and use it in rtc get instead of a bunch of code in one function? Other than that great job! 

Edit : you also forgot the synopsis and make better docs

**Review by amanuel2 — APPROVED** [review]
Changed to extern functions in header, better docs,  selected rtc functions.

**Comment by double-fault** [comment]
Nope. The time command should also be able to change the current time. I'm going to add that

**Comment by amanuel2** [comment]
@Fortunate-MAN #135

**Pull request merged**
